### ISSUE TITLE
Need license

### ISSUE THREAD

**Issue by jackpal** [jackpal/picasawebuploader#15]
People have been asking for a license.

The code contains code taken from this blog post (you'll need to use archive.org to find it.)

http://nathanvangheem.com/news/moving-to-picasa-update

That code does not have a license.

I notice that Nathan Van Gheem is now on github as vahgheem. I'll email him to see what license he used for the original code.

**Comment by jackpal** [comment]
Contacted Nathan, got permission to use whatever license I wanted, chose Apache 2.0, added license file.

**Comment by pjjjv** [comment]
Thanks, I'll put up my version shortly? Do you prefer a pull request or just a fork? Again, don't expect too much, the APIs have gone down the drain AFAIK.

**Comment by jackpal** [comment]
A pull request would be nice. But you're welcome to fork if you prefer....

I don't have any easy way of testing the script any more, so I'll be
reading the code, but taking your word on its functionality.

**Comment by pjjjv** [comment]
Pull request created.
